- name: subscription
  block:

    - name: "RHSM | Register (safe, NO shell, single call)"
      ansible.builtin.command:
        argv:
          - subscription-manager
          - register
          - --activationkey={{ satellite_register_ak | trim }}
          - --org={{ satellite_register_org | trim }}
          - "{{ (satellite_register_force | default(false)) | ternary('--force', omit) }}"
      register: rhsm_register
      changed_when: false
      failed_when: rhsm_register.rc != 0
      timeout: 300

  rescue:

    # --- Collect info for decision making (always safe) ---
    - name: "RHSM | Stat uuid facts file"
      ansible.builtin.stat:
        path: /etc/rhsm/facts/uuid.facts
      register: uuid_file

    - name: "RHSM | Detect duplicate UUID error"
      ansible.builtin.set_fact:
        rhsm_duplicate_uuid: >-
          {{
            (rhsm_register is defined)
            and (
              'matches other registered hosts' in (rhsm_register.stderr | default(''))
              or 'This system is already registered' in (rhsm_register.stderr | default(''))
            )
          }}

    # --- Fix only when it is truly a duplicate UUID case ---
    - name: "RHSM | Create uuid.facts for VM guest when duplicate detected (one-time)"
      ansible.builtin.copy:
        dest: /etc/rhsm/facts/uuid.facts
        owner: root
        group: root
        mode: '0644'
        content: "\"dmi.system.uuid\":\"{{ lookup('ansible.builtin.pipe', 'uuidgen') }}\"\n"
      when:
        - rhsm_duplicate_uuid | bool
        - not (uuid_file.stat.exists | default(false))
        - (ansible_facts['virtualization_role'] | default('')) == 'guest'

    # --- Retry register if we applied fix OR if duplicate was detected but file existed already ---
    - name: "RHSM | Retry register after duplicate-UUID handling"
      ansible.builtin.command:
        argv:
          - subscription-manager
          - register
          - --activationkey={{ satellite_register_ak | trim }}
          - --org={{ satellite_register_org | trim }}
          - "{{ (satellite_register_force | default(false)) | ternary('--force', omit) }}"
      register: rhsm_register_retry
      changed_when: false
      failed_when: rhsm_register_retry.rc != 0
      timeout: 300
      when:
        - rhsm_duplicate_uuid | bool

    # --- Hard fail for other errors (network/cert/org/ak/etc.) ---
    - name: "RHSM | Fail if register failed (not duplicate UUID or retry failed)"
      ansible.builtin.fail:
        msg: >-
          RHSM register failed.
          rc={{ (rhsm_register_retry.rc if (rhsm_register_retry is defined) else (rhsm_register.rc if (rhsm_register is defined) else 'n/a')) }}
          stderr={{ (rhsm_register_retry.stderr if (rhsm_register_retry is defined) else (rhsm_register.stderr if (rhsm_register is defined) else 'n/a')) }}
      when:
        - not (rhsm_duplicate_uuid | default(false) | bool) or (rhsm_register_retry is not defined)